name: HACT.Dtos

on:
  release:
    types: [ published ]


jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: set artifacts directory env
        run: echo "ARTIFACTS_DIRECTORY=artifacts" >> $GITHUB_ENV
      - name: set env var
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Build
        run: dotnet build
      - name: Package project
        run: |
          dotnet pack --configuration Release /p:Version=${{env.RELEASE_VERSION}} -o ${{env.ARTIFACTS_DIRECTORY}}
      - name: Publish project
        env:
          PACKAGE_PATH: ${{env.ARTIFACTS_DIRECTORY}}/HACT.Dtos.${{env.RELEASE_VERSION}}.nupkg
        run: |
          echo $PWD
          dotnet nuget push $PACKAGE_PATH --api-key ${{secrets.TOKEN}} --source https://nuget.pkg.github.com/LBHackney-IT/index.json
